# Generated by Django 5.2.14 on 2026-06-01 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['visibility', 'state', '-created_at'],
                name='project_vis_state_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(
                fields=['owner', '-created_at'],
                name='project_owner_created_idx',
            ),
        ),
    ]
