# Generated by Django 5.2.14 on 2026-06-01 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_vis_state_created_idx_and_more'),
        ('tasks', '0002_task_watcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['project', 'status', 'due_at'],
                name='tasks_project_status_due_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['project', 'assignee', 'due_at'],
                name='tasks_project_assignee_due_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['project', 'priority', '-created_at'],
                name='tasks_project_priority_idx',
            ),
        ),
    ]
