FROM squidfunk/mkdocs-material:9 AS docs-build

WORKDIR /docs
COPY mkdocs.yml /docs/mkdocs.yml
COPY docs /docs/docs
RUN mkdocs build --site-dir /site

FROM nginx:1.27-alpine

COPY deploy/release/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=docs-build /site /usr/share/nginx/html/docs

EXPOSE 80
