apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-management-api
  namespace: project-management
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.example.com
      secretName: project-management-api-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-management-api
                port:
                  name: http
