apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-management-media
  namespace: project-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
