# Generated by Django 5.2.14 on 2026-05-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d/")),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
